name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.ACR_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.ACR_PASSWORD}}
      run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ashrafd0cker/knowledgefactory:$(date +%s)
    - name: Docker Push
      run: docker push ${{ secrets.ACR_ENDPOINT }}/ashrafd0cker/knowledgefactory
